Output cause of error when FileSystem.copy_entries method was failed.
- befor the change

    $ knife upload nodes/node.json
    ERROR: nodes/node.json failed to write: HTTP error writing: 400 "Bad Request"

- after the change

    $ knife upload nodes/node.json
    ERROR: nodes/node.json failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Invalid key test in request body"]}